<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5fb1918b3be7b',
	'title' => 'Global theme options',
	'fields' => array(
		array(
			'key' => 'field_5fb1919caa2e7',
			'label' => 'Global email address',
			'name' => 'global_email_address',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb191c1aa2e9',
			'label' => 'Global address lines',
			'name' => 'global_address_lines',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add address lines',
			'sub_fields' => array(
				array(
					'key' => 'field_5fb191dcaa2ea',
					'label' => 'Address lines',
					'name' => 'address_line',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Address line',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5fb1920faa2eb',
			'label' => 'Global socials',
			'name' => 'global_socials',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add socials',
			'sub_fields' => array(
				array(
					'key' => 'field_5fb19229aa2ec',
					'label' => 'Social image',
					'name' => 'global_social_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5fb19254aa2ed',
					'label' => 'Social link',
					'name' => 'global_social_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Social link',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fb42cfe99ab3',
	'title' => 'Learning resources',
	'fields' => array(
		array(
			'key' => 'field_5fb42cfe9e986',
			'label' => 'Learning resource title',
			'name' => 'learning_resources_pt_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb42d6a57117',
			'label' => 'Learning resource upload',
			'name' => 'learning_resource_upload',
			'type' => 'file',
			'instructions' => 'Upload learning resource here. Also, please select a category to the right of the admin screen.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fb42cfe9e996',
			'label' => 'Learning resource date',
			'name' => 'learning_resources_pt_date',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5fb42cfe9e9a5',
			'label' => 'Learning resource overview',
			'name' => 'learning_resources_pt_overview',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5fb42cfe9e9b2',
			'label' => 'Learning resource link',
			'name' => 'learning_resources_pt_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'learning_resources',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fb0617e6a426',
	'title' => 'Page sections',
	'fields' => array(
		array(
			'key' => 'field_5fb065c75b952',
			'label' => 'Add page section',
			'name' => 'add_page_section',
			'type' => 'repeater',
			'instructions' => 'Add your page sections here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_5fb0662c5b953',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add page section',
			'hide_collapse' => 0,
			'collapse_all_repeater' => 0,
			'btn-icon-only' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_5fb0662c5b953',
					'label' => 'Section type',
					'name' => 'page_section_type',
					'type' => 'select',
					'instructions' => 'Choose your section type.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'banner' => 'Banner',
						'scrollgal' => 'Scrolling gallery ~ style 1',
						'scrollgalllink' => 'Scrolling gallery ~ style 2',
						'fullwidthtext' => 'Full width text',
						'splittext' => 'Split text',
						'splitimagetext' => 'Split Image and text',
						'splitroundimagetext' => 'Split round Image and text',
						'splitimageanimations' => 'Split animations and text',
						'fullwidthanimatedsection1' => 'Animated icons ~ full-width style 1',
						'fullwidthanimatedsection2' => 'Animated icons ~ full-width style 2',
						'fullwidthbackgroundimagegradient' => 'Background image with gradient and text',
						'rolloverboxes' => 'Rollover boxes ~ Large',
						'rolloverboxessmall' => 'Rollover boxes ~ Small',
						'tabbedcontent' => 'Tabbed content',
						'meettheteam' => 'Meet the team',
						'dropdowncontentsection' => 'Dropdown content section',
						'workshopcategorysection' => 'Workshop category section',
						'videosection' => 'Video section',
						'contactformsection' => 'Contact form',
						'learningresources' => 'Learning resources',
						'teammemspt' => 'Team members',
						'upcomingevents' => 'Upcoming events',
						'workshops' => 'Workshops',
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5fb09ea5d755f',
					'label' => 'Section background colour',
					'name' => 'section_colour',
					'type' => 'color_picker',
					'instructions' => 'Select section colour or enter a colour value.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
				),
				array(
					'key' => 'field_5fb4524b7850e',
					'label' => 'Section text colour',
					'name' => 'section_text_colour',
					'type' => 'color_picker',
					'instructions' => 'Select section text colour or enter a colour value.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '#000000',
				),
				array(
					'key' => 'field_5fb16404d8426',
					'label' => 'Banner slides',
					'name' => 'banner_slides',
					'type' => 'repeater',
					'instructions' => 'Add your banner slides here.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'banner',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_5fb16391d8424',
					'min' => 1,
					'max' => 100,
					'layout' => 'block',
					'button_label' => 'Add hero banner slide',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb16391d8424',
							'label' => 'Banner title',
							'name' => 'banner_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Banner title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb163bdd8425',
							'label' => 'Banner strapline',
							'name' => 'banner_strapline',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Banner strapline',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => 'wpautop',
						),
						array(
							'key' => 'field_5fb1651d7e9f6',
							'label' => 'Slide image',
							'name' => 'banner_slide_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb166861c26e',
							'label' => 'Slide video from url',
							'name' => 'banner_slide_video_url',
							'type' => 'text',
							'instructions' => 'Paste video URL here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Video URL',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb166df1c26f',
							'label' => 'Slide video from library',
							'name' => 'slide_video_from_library',
							'type' => 'file',
							'instructions' => 'Upload or choose from media library.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb165e07e9fc',
					'label' => 'Scrolling carousel 1 title',
					'name' => 'scrolling_carousel_1_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'scrollgal',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Carousel title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb165407e9f7',
					'label' => 'Scrolling carousel 1 slides',
					'name' => 'scrolling_gallery_1_slides',
					'type' => 'repeater',
					'instructions' => 'Add your carousel slides here.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'scrollgal',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add slide',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb165407e9fa',
							'label' => 'Carousel style 1 image',
							'name' => 'carousel_style_1_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb165b07e9fb',
							'label' => 'Carousel style 1 link',
							'name' => 'carousel_style_1_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb16910cc9a6',
					'label' => 'Scrolling carousel 2 title',
					'name' => 'scrolling_carousel_2_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'scrollgalllink',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Carousel title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb16930cc9a7',
					'label' => 'Scrolling carousel 2 slides',
					'name' => 'scrolling_gallery_2_slides',
					'type' => 'repeater',
					'instructions' => 'Add your carousel slides here.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'scrollgalllink',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add slide',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb16930cc9a8',
							'label' => 'Carousel item image',
							'name' => 'carousel_item_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb16971cc9aa',
							'label' => 'Carousel item title',
							'name' => 'carousel_item_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb169bdcc9ab',
							'label' => 'Carousel item text',
							'name' => 'carousel_item_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb16930cc9a9',
							'label' => 'Carousel item Read more link',
							'name' => 'carousel_item_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb16cae8f978',
					'label' => 'Split text section left',
					'name' => 'split_text_section_left',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splittext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5fb48362183b5',
					'label' => 'Left arrowed content',
					'name' => 'split_left_arrowed_content',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splittext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'hide_collapse' => 0,
					'collapse_all_repeater' => 0,
					'btn-icon-only' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_5fb483bd183b6',
							'label' => 'Title',
							'name' => 'title_arrowed_content',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb483df183b7',
							'label' => 'Text',
							'name' => 'text_arrowed_content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb16ce78f979',
					'label' => 'Split text section right',
					'name' => 'split_text_section_right',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splittext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5fb4840b183b8',
					'label' => 'Right arrowed content',
					'name' => 'split_right_arrowed_content',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splittext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'hide_collapse' => 0,
					'collapse_all_repeater' => 0,
					'btn-icon-only' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_5fb4840c183b9',
							'label' => 'Title',
							'name' => 'title_right_arrowed_content',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb4840c183ba',
							'label' => 'Text',
							'name' => 'text_right_arrowed_content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb16d1193c5e',
					'label' => 'Split text section enquire now link',
					'name' => 'split_text_section_enquire_now_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splittext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb16e070f6a6',
					'label' => 'Video section title',
					'name' => 'video_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'videosection',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Video section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb16e2a0f6a7',
					'label' => 'Video section videos',
					'name' => 'video_section_videos',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'videosection',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add video',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb16e3f0f6a8',
							'label' => 'Video url',
							'name' => 'vid_section_video_url',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Video URL',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb16e570f6a9',
							'label' => 'Video from media library',
							'name' => 'vid_section_video_from_media_library',
							'type' => 'file',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb16f8fd3f35',
							'label' => 'Video title',
							'name' => 'single_vid_video_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Video title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb16f75d3f34',
					'label' => 'Video section link',
					'name' => 'video_section_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'videosection',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Video section link',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb17a901665a',
					'label' => 'Split section image',
					'name' => 'split_section_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5fb17b281665c',
					'label' => 'Split section text blocks',
					'name' => 'split_section_text_blocks',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add block content',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb17c272bde5',
							'label' => 'Block title',
							'name' => 'split_section_block_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Block title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb17ca2838ed',
							'label' => 'Block subtitle',
							'name' => 'split_section_block_subtitle',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Block subtitle',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb17c542bde6',
							'label' => 'Block text',
							'name' => 'split_section_block_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Block text',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb17b021665b',
					'label' => 'Split section round image',
					'name' => 'split_section_round_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5fb2049035238',
					'label' => 'Select to show image left',
					'name' => 'select_to_show_image_left',
					'type' => 'checkbox',
					'instructions' => 'By default, the image will show to the right. Please check this box to show image to the left.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'alignleft' => 'Align image left of text',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5fb1edd8fea37',
					'label' => 'Image width px',
					'name' => 'split_section_round_image_size_px',
					'type' => 'number',
					'instructions' => 'Set the image width here',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Image width number',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5fb2142bd3a83',
					'label' => 'Image roundness px',
					'name' => 'split_section_round_image_border_radius_px',
					'type' => 'number',
					'instructions' => '0 for a square image, 50 + for a rounder image.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Image roundness number',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5fb1eeaefc8b9',
					'label' => 'Image vertical position in pixels',
					'name' => 'split_section_round_image_pos_px',
					'type' => 'number',
					'instructions' => 'Set Image position here. Minus values will place the image higher and + values lower.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Image vertical position in pixels',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5fb21497d3a84',
					'label' => 'Image horizontal position in pixels',
					'name' => 'split_section_round_image_left_px',
					'type' => 'number',
					'instructions' => 'Set Image position here. Minus values will place the image further left and + values further right.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 'Image horizontal position in pixels',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_5fb1f000acf77',
					'label' => 'Split section title',
					'name' => 'splitimagetextround_split_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb17b601665d',
					'label' => 'Split section text',
					'name' => 'splitimagetextround_split_section_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5fb1e0429cd7e',
					'label' => 'Boxed section title',
					'name' => 'small_boxed_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'rolloverboxessmall',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Boxed section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1e0619cd7f',
					'label' => 'Small boxed content',
					'name' => 'small_boxed_content',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'rolloverboxessmall',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add small box',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb1e0619cd80',
							'label' => 'Box background color',
							'name' => 'small_rollover_box_background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5fb1e0619cd81',
							'label' => 'Small box background image',
							'name' => 'small_rollover_box_background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb1e0619cd82',
							'label' => 'Box title',
							'name' => 'small_rollover_box_section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Box title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb1e0619cd83',
							'label' => 'Box text',
							'name' => 'small_rollover_box_section_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Box text',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5fb1e0619cd84',
							'label' => 'Box link',
							'name' => 'small_rollover_box_section_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'View more URL',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb181cc5245d',
					'label' => 'Boxed section title',
					'name' => 'large_boxed_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'rolloverboxes',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Boxed section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb17d66247bd',
					'label' => 'Large boxed content',
					'name' => 'large_boxed_content',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'rolloverboxes',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add large box',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb17de6247c1',
							'label' => 'Box background color',
							'name' => 'large_box_background_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5fb17e09247c3',
							'label' => 'Box background image',
							'name' => 'large_box_background_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb17d44247bc',
							'label' => 'Box title',
							'name' => 'large_box_section_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Box title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb17dae247be',
							'label' => 'Box text',
							'name' => 'large_box_section_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Box text',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5fb17dd1247bf',
							'label' => 'Box link',
							'name' => 'large_box_section_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'View more URL',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb182b8761cf',
					'label' => 'Section title',
					'name' => 'tabbed_content_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'tabbedcontent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Tabbed section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1832b761d0',
					'label' => 'Tabbed content slides',
					'name' => 'tabbed_content_slides',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'tabbedcontent',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add tabbed content',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb1834f761d1',
							'label' => 'Tabs titles',
							'name' => 'single_tabs_titles',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb18380761d2',
							'label' => 'Tabs text',
							'name' => 'single_tabs_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb184ce9b659',
					'label' => 'Contact section title',
					'name' => 'contact_form_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'contactformsection',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Contact form section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb184fb9b65a',
					'label' => 'Contact section email address',
					'name' => 'contact_section_email_address',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'contactformsection',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Contact section email address',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1851e9b65c',
					'label' => 'Contact section socials',
					'name' => 'contact_form_section_socials',
					'type' => 'repeater',
					'instructions' => 'Add your social media links in here. If left empty here, by default these will display the socials set up in the Theme Settings admin tab.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'contactformsection',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add socials',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb185a89b65d',
							'label' => 'Socials link',
							'name' => 'socials_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Socials link',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb185b99b65e',
							'label' => 'Socials icon',
							'name' => 'socials_icon',
							'type' => 'image',
							'instructions' => 'Add your social media icon here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb1bab04b441',
					'label' => 'Team section title',
					'name' => 'team_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'meettheteam',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Team section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1985e3a5ff',
					'label' => 'Meet the team profiles',
					'name' => 'meet_the_team_profile_links',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'meettheteam',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add team member',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb199003a603',
							'label' => 'Team member profile image',
							'name' => 'team_member_profile_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb198a23a600',
							'label' => 'Team member name',
							'name' => 'team_member_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Team member name',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb198cc3a601',
							'label' => 'Team member job title',
							'name' => 'team_member_job_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Team member job title',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fb198da3a602',
							'label' => 'Team member email address',
							'name' => 'team_member_email_address',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Team member email address',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb1cb6697ae5',
					'label' => 'Section title',
					'name' => 'split_animations_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitimageanimations',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1ca84522ac',
					'label' => 'Section text',
					'name' => 'split_animations_section_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitimageanimations',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5fb1cb8a97ae6',
					'label' => 'Section title',
					'name' => 'split_animations_section_title_right',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitimageanimations',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1cbc497ae8',
					'label' => 'Section animations',
					'name' => 'split_animations_section_animations',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitimageanimations',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add animations',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb1cbec97ae9',
							'label' => 'Animation icons',
							'name' => 'split_animations_section_animation_icons',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb1d00f46793',
					'label' => 'Section animations - thirds',
					'name' => 'split_animations_section_animations_full_1',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthanimatedsection1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add animations',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb1d00f46794',
							'label' => 'Animation icons',
							'name' => 'split_animations_section_animation_icons_full_1',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb1d02546795',
							'label' => 'Animations text',
							'name' => 'animations_text_full_1',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb1d5c79e214',
					'label' => 'Section title',
					'name' => 'split_animations_section_title_full_fourths',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthanimatedsection2',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb1d5516c71c',
					'label' => 'Section animations - fourths',
					'name' => 'split_animations_section_animations_full_2',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthanimatedsection2',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'Add animations',
					'sub_fields' => array(
						array(
							'key' => 'field_5fb1d5516c71d',
							'label' => 'Animation icons',
							'name' => 'split_animations_section_animation_icons_full_2',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb431b85060f',
					'label' => 'Section title',
					'name' => 'full_width_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthtext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb430879fd1b',
					'label' => 'Full width text',
					'name' => 'full_width_text_section',
					'type' => 'wysiwyg',
					'instructions' => 'Add your text here.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthtext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5fb4419b68abe',
					'label' => 'Background image',
					'name' => 'image_grad_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthbackgroundimagegradient',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5fb44379cfc58',
					'label' => 'Left or right text',
					'name' => 'image_grad_text_left',
					'type' => 'checkbox',
					'instructions' => 'Check this box to position your text to the left of the section.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthbackgroundimagegradient',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'textleft' => 'Check to position text to the left',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5fb442b5c85ae',
					'label' => 'Section title',
					'name' => 'image_grad_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthbackgroundimagegradient',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Section title',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb442d9c85af',
					'label' => 'Section text',
					'name' => 'image_grad_text',
					'type' => 'wysiwyg',
					'instructions' => 'Section text here.',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'fullwidthbackgroundimagegradient',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array(
					'key' => 'field_5fb45826c07c6',
					'label' => 'Show learning resources on this page',
					'name' => 'learning_resources',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'learningresources',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'showlearningresources' => 'Show learning resources section',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5fb4627d9e01a',
					'label' => 'Show team members on this page',
					'name' => 'show_team_members_on_this_page',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'teammemspt',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'showteammems' => 'Show team members section',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5fb462d99e01b',
					'label' => 'Show upcoming events on this page',
					'name' => 'show_upcoming_events_on_this_page',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'upcomingevents',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'showupcomingevents' => 'Show upcoming events section',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5fb4663b62d67',
					'label' => 'Section title',
					'name' => 'upcoming_events_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'upcomingevents',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb4665c62d68',
					'label' => 'Section text',
					'name' => 'upcoming_events_section_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'upcomingevents',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5fb463129e01c',
					'label' => 'Show workshops on this page',
					'name' => 'show_workshops_on_this_page',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'workshops',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'showworkshops' => 'Show workshops section',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_5fb470e75038f',
					'label' => 'Section title',
					'name' => 'our_workshops_section_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'workshops',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb4710950390',
					'label' => 'Section text',
					'name' => 'our_workshops_section_text',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'workshops',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5fb4890b635bd',
					'label' => 'Dropdown icons content',
					'name' => 'dropdown_icons_content',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => '',
					'hide_collapse' => 0,
					'collapse_all_repeater' => 0,
					'btn-icon-only' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_5fb4890c635be',
							'label' => 'Icon',
							'name' => 'dropdown_icon_content_icons',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5fb4890c635bf',
							'label' => 'Text',
							'name' => 'dropdown_icons_text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb48b894cedf',
					'label' => 'Dropdown clients content',
					'name' => 'dropdown_clients_content',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => '',
					'hide_collapse' => 0,
					'collapse_all_repeater' => 0,
					'btn-icon-only' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_5fb48b894cee0',
							'label' => 'Icon',
							'name' => 'dropdown_clients_content_icons',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'medium',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
				),
				array(
					'key' => 'field_5fb48bfc93bd3',
					'label' => 'Dropdown content image',
					'name' => 'dropdown_content_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5fb48c3193bd5',
					'label' => 'Dropdown content title',
					'name' => 'dropdown_content_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fb48c4e93bd6',
					'label' => 'Dropdown content text',
					'name' => 'dropdown_content_text',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fb0662c5b953',
								'operator' => '==',
								'value' => 'splitroundimagetext',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'featured_image',
		6 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fb42aba4e9bc',
	'title' => 'Team members',
	'fields' => array(
		array(
			'key' => 'field_5fb42b2969dd6',
			'label' => 'Team member image',
			'name' => 'team_member_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5fb42aba5c8dd',
			'label' => 'Team member name',
			'name' => 'team_member_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb42b0969dd4',
			'label' => 'Team member work role',
			'name' => 'team_member_work_role',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb42af769dd3',
			'label' => 'Team member email',
			'name' => 'team_member_email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'team_members',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fb429179c410',
	'title' => 'Upcoming events',
	'fields' => array(
		array(
			'key' => 'field_5fb42928c6add',
			'label' => 'Event title',
			'name' => 'event_pt_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb429a6c6adf',
			'label' => 'Event date',
			'name' => 'event_pt_date',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5fb42944c6ade',
			'label' => 'Event overview',
			'name' => 'event_pt_overview',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5fb429d9c6ae0',
			'label' => 'Register link',
			'name' => 'event_pt_register_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'upcoming_events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_5fb42c1f7f5dd',
	'title' => 'Workshops',
	'fields' => array(
		array(
			'key' => 'field_5fb42c1f83d99',
			'label' => 'Workshop title',
			'name' => 'workshop_pt_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5fb42c1f83dc2',
			'label' => 'Workshop date',
			'name' => 'workshop_pt_date',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5fb42c1f83de8',
			'label' => 'Workshop overview',
			'name' => 'workshop_pt_overview',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_5fb42c1f83df7',
			'label' => 'Workshop link',
			'name' => 'workshop_pt_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'learning_workshops',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

endif;